export enum BreadcrumbTitle {
  Application = "Application",
  CreateApplication = "Create application",
  DetailsApplication = "Details application",
  IntegrationsApplication = "Integrations application",
  SecurityApplication = "Security application",
  Users = "Users",
  Roles = "Roles",
  Settings = "Settings",
  Account = "Tenant",
  Project = "Project",
  Category = "Category",
  SubCategory = "Sub category",
  DashBoard = "Dashboard",
  Issue = "Menu",
  UserManagement = "User management",
  SlaManagement = "Sla management",
  Detail = "Detail",
  IssueDetail = "Issue detail",
  Profile = "Profile",
  Home = "Home",
}
