export const DataMock = {
  Menu: {
    food: [
      { id: 1, name: "ยำไส้กรอก", price: 40, have_order: true },
      { id: 2, name: "ยำหมูยอ", price: 50, have_order: true },
      { id: 3, name: "ยำไข่แดงเค็ม", price: 60, have_order: true },
      { id: 4, name: "ยำหมูยอไข่แดงเค็ม", price: 70, have_order: true },
      { id: 5, name: "ยำสามชั้นทอด", price: 70, have_order: true },
      { id: 6, name: "ยำคอหมูทอด", price: 70, have_order: false },
      { id: 7, name: "ยำหอยแครง", price: 70, have_order: false },
      { id: 8, name: "ยำปลาหมึก", price: 70, have_order: true },
      { id: 9, name: "ยำกุ้งสด", price: 70, have_order: false },
      { id: 10, name: "ยำกุ้งสุก", price: 70, have_order: true },
      { id: 11, name: "ยำกุ้งทูโทน", price: 70, have_order: true },
      { id: 12, name: "ยำปูม้า", price: 80, have_order: true },
      { id: 13, name: "ยำปูม้าสุก", price: 80, have_order: false },
      { id: 14, name: "ยำแซลมอน", price: 100, have_order: true },
      { id: 15, name: "ยำแซลมอนหอยแครง", price: 150, have_order: true },
      { id: 16, name: "ยำแซลมอนกุ้งสด", price: 150, have_order: false },
      { id: 17, name: "ยำแซ่บสะเดิด", price: 200, have_order: true },
      { id: 18, name: "สามชั้นทอด", price: 80, have_order: true },
      { id: 19, name: "คอหมูทอด", price: 80, have_order: true },
      { id: 20, name: "ปีกไก่ทอด", price: 50, have_order: true },
      { id: 21, name: "หมูยอทอด", price: 50, have_order: true },
      { id: 22, name: "ข้าวสวย", price: 10, have_order: true },
      { id: 23, name: "ข้าวเหนียว", price: 10, have_order: true },
      { id: 24, name: "ขนมจีน", price: 10, have_order: true },
      { id: 25, name: "น้ำโค้ก", price: 30, have_order: true },
    ],
  },
};
